#!/usr/bin/env bash
set -euo pipefail

init() {
    mkdir debian
    name=${PWD##*/}
    cat > debian/control << EOL
Package: ${name}
Description: ${name}
Version: 0.0.1
Depends:
Maintainer: Jane Doe <jane@doe.com>
Architecture: all
Section: misc
Priority: required
EOL
}

build() {
    rm -r .package
    mkdir -p .package/DEBIAN

    cp debian/control .package/DEBIAN/

    # Copy maintainer scripts
    for file in preinst postinst prerm postrm; do
        if [[ -f debian/${file} ]]; then
            cp "debian/${file}" .package/DEBIAN/
            chmod 0755 ".package/DEBIAN/${file}"
        fi
    done

    # Fail if no .debpack
    cat .debpack | while IFS= read -r line || [[ -n ${line} ]]; do
        src=$(echo "${line}" | cut -f1)
        dst=.package$(echo "${line}" | cut -f2)
        mkdir -p "${dst%/*}"
        # Allow source wildcards
        # shellcheck disable=SC2086
        cp ${src} "${dst}"
    done

    dpkg-deb --build .package
    dpkg-name .package.deb
}

case ${1:-build} in
    init)
        init
        ;;
    build)
        build
        ;;
    *)
        echo "Usage: $0 {build,init}"
        exit 1
        ;;
esac
